// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ysfTPLwooajGLFIwltXa3gIou8WBU0M',
    appId: '1:952745424037:web:a7e762456a58b0fc72494c',
    messagingSenderId: '952745424037',
    projectId: 'flutter-test-app-abb70',
    authDomain: 'flutter-test-app-abb70.firebaseapp.com',
    storageBucket: 'flutter-test-app-abb70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8CSJlxCJrbtm_RWtEmHc5O3xanJwoLBE',
    appId: '1:952745424037:android:cb2ef7bf9efea7ee72494c',
    messagingSenderId: '952745424037',
    projectId: 'flutter-test-app-abb70',
    storageBucket: 'flutter-test-app-abb70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAImQc5EaVbZfMbGp1YM7BD-vF-Qv2Eqro',
    appId: '1:952745424037:ios:b93cd97fa7354fd372494c',
    messagingSenderId: '952745424037',
    projectId: 'flutter-test-app-abb70',
    storageBucket: 'flutter-test-app-abb70.appspot.com',
    iosClientId:
        '952745424037-r9057lut4h8q7eg5tklqf1ln5qiqkopp.apps.googleusercontent.com',
    iosBundleId: 'com.example.provProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAImQc5EaVbZfMbGp1YM7BD-vF-Qv2Eqro',
    appId: '1:952745424037:ios:d689a7567ae688c072494c',
    messagingSenderId: '952745424037',
    projectId: 'flutter-test-app-abb70',
    storageBucket: 'flutter-test-app-abb70.appspot.com',
    iosClientId:
        '952745424037-92msatrthf57phahufvfhsmph859qtt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.provProject.RunnerTests',
  );
}
